#!/usr/bin/env python3
"""Bundle the browser UI, transport and programmer UF2 into one portable HTML."""
import argparse
import base64
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUTPUTS = (HERE / "index.html", ROOT / "docs/index.html")


def bundle():
    manifest = json.loads((ROOT / "dist/manifest.json").read_text())
    uf2 = (ROOT / "dist/hanshow_pio_bridge.uf2").read_bytes()
    if hashlib.sha256(uf2).hexdigest() != manifest["uf2_sha256"]:
        raise ValueError("Programmer UF2 does not match its manifest")
    html = (HERE / "index.template.html").read_text()
    html = html.replace("@@PROGRAMMER_UF2@@", "data:application/octet-stream;base64," + base64.b64encode(uf2).decode("ascii"))
    html = html.replace("@@PROGRAMMER_VERSION@@", manifest["version"])
    for name in ("sws.js", "app.js"):
        marker = f'<script src="{name}"></script>'
        if html.count(marker) != 1:
            raise ValueError(f"Expected one template script: {name}")
        source = (HERE / name).read_text()
        # Prevent an HTML end tag inside a JS string/comment terminating the script.
        source = re.sub(r"</script", lambda match: "<\\/script", source, flags=re.I)
        html = html.replace(marker, f"<script>\n/* Bundled from {name}. */\n{source}</script>")
    if re.search(r"<script\b[^>]*\bsrc\s*=", html, re.I) or "@@PROGRAMMER_" in html:
        raise ValueError("Bundle still contains an external script or placeholder")
    return "<!-- Generated by firmware-dumper/build_standalone.py; edit the template and JS sources. -->\n" + html


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify checked-in HTML matches its sources")
    args = parser.parse_args()
    content = bundle().encode("utf-8")
    for path in OUTPUTS:
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                raise SystemExit(f"Stale standalone HTML: {path.relative_to(ROOT)}; run {parser.prog}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    print(f"{'Verified' if args.check else 'Built'} standalone HTML: {len(content)} bytes; CSS, JavaScript and UF2 included")


if __name__ == "__main__":
    main()
